version: 2
jobs:
  build:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:1.17.2
    working_directory: /go/src/github.com/hashicorp/vault-plugin-auth-kubernetes
    steps:
      - checkout
      - run:
          name: "Setup Environment"
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
      - run:
          name: "Run Tests"
          command: |
            make test
