---
name: Backport Assistant Runner for Vault Plugin Eco Projects
on:
  pull_request_target:
    types:
      - closed
      - labeled
jobs:
  backport-targeted-release-branch:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.3.1
    steps:
      - name: Backport changes to targeted release branch
        env:
          BACKPORT_LABEL_REGEXP: "backport/vault-(?P<target>\\d+\\.\\d+\\.\\w+)"
          BACKPORT_TARGET_TEMPLATE: "release/vault-{{.target}}"
          BACKPORT_MERGE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.VAULT_ECO_GITHUB_TOKEN }}
        run: |
          backport-assistant backport -merge-method=squash -gh-automerge
